### ISSUE TITLE
Description of installation process does not work

### ISSUE THREAD

**Issue by AiCaptain** [CodiTramuntana/decidim-verifications-csv_emails#18]
It seems that the preferred way of downloading repositories from github is to use the https url.  There is no ssh option anymore.

So the url  in the line
`gem 'decidim-verifications-csv_email', git: 'git@github.com:CodiTramuntana/decidim-verifications-csv_emails.git'`
have to be changed to 
`gem 'decidim-verifications-csv_email', git: 'https://github.com/CodiTramuntana/decidim-verifications-csv_emails.git'`

**Comment by laurajaime** [comment]
@AiCaptain thanks for the issue!
